# Generated by Django 3.2 on 2021-05-05 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210505_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 12, 32, 13, 553636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
